name: Publish to TestPyPI

on:
  workflow_run:
    workflows: [Build distribution]
    types:
      - completed

jobs:
  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI


    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/imaug
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/